#!/usr/bin/env bash

CWD=$(pwd) 
DATE=$(date +"%Y%m%d%H%M")
files="vim vimrc"

# clear old symlinks
if [ -h $HOME/.vimrc ] ; then
  rm $HOME/.vimrc
fi

# clear old symlink or backup old settings, if there are any
if [ -h $HOME/.vim ] ; then
  rm $HOME/.vim
elif [ "$CWD" != "$HOME/.vim" ] ; then
  for file in $files; do
    echo "Renaming existing $file to $file-$DATE"
    mv $HOME/.$file $HOME/.$file-$DATE
  done
  # output links
  echo "Creating symlink to $CWD in home directory."
  ln -s $CWD $HOME/.vim
fi

# final flourish
ln -s $HOME/.vim/vimrc $HOME/.vimrc
mkdir -p $HOME/.vim/{tmp,undo,view}
git submodule init
wait
git submodule update --recursive
wait
printf "All done!\n"
