#!/usr/bin/env bash

CWD=$(pwd) 
DATE=$(date +"%Y%m%d%H%M")
files="vim vimrc"

# backup old settings
for file in $files; do
  echo "Renaming existing $file to $file-$DATE"
  mv $HOME/.$file $HOME/.$file-$DATE
done

# output links
echo "Creating symlink to $CWD in home directory."
ln -s $CWD $HOME/.vim

# final flourish
ln -s $HOME/.vim/vimrc $HOME/.vimrc
mkdir -p $HOME/.vim/{tmp,undo,view}
git submodule init
wait
git submodule update --recursive
wait
printf "All done!\n"
